#!/usr/bin/env -S uv tool run dotlocalslashbin --input
[git-jump]
url = "https://raw.githubusercontent.com/git/git/refs/tags/v2.52.0/contrib/git-jump/git-jump"

["osc52.sh"]
url = "https://raw.githubusercontent.com/libapps/libapps-mirror/refs/tags/nassh-0.71/hterm/etc/osc52.sh"

[wcurl]
url = "https://github.com/curl/wcurl/releases/download/v2025.11.09/wcurl"

# bin/github.toml
# Copyright Keith Maxwell
# SPDX-License-Identifier: CC0-1.0
