#!/usr/bin/env -S uv tool run dotlocalslashbin --input
[a4]
url = "https://github.com/maxwell-k/a4/releases/download/0.2.1/a4"
expected = "a68b6bd92be782e109c5066da692d6463c807cf5213b732c4fe5e9e51bd194eb" # bin/update.py a4
version = "--version"
modifier = "SHA256SUMS"

[actionlint]
url = "https://github.com/rhysd/actionlint/releases/download/v1.7.9/actionlint_1.7.9_linux_amd64.tar.gz"
expected = "233b280d05e100837f4af1433c7b40a5dcb306e3aa68fb4f17f8a7f45a7df7b4" # bin/update.py actionlint
modifier = "_checksums.txt"
ignore = [
  "LICENSE.txt",
  "README.md",
  "docs/README.md",
  "docs/api.md",
  "docs/checks.md",
  "docs/config.md",
  "docs/install.md",
  "docs/reference.md",
  "docs/usage.md",
  "man/actionlint.1",
]
version = "-version"

[deno]
url = "https://github.com/denoland/deno/releases/download/v2.6.3/deno-x86_64-unknown-linux-gnu.zip"
expected = "9e1c284e0440ac27f1933aa98edcfe0ef3d1ae7c8f755d67682d182a7d1afc0f" # bin/update.py deno
target = "~/.deno/bin/deno"
version = "--version"
modifier = ".sha256sum"

[dprint]
url = "https://github.com/dprint/dprint/releases/download/0.50.2/dprint-x86_64-unknown-linux-gnu.zip"
expected = "95c7e633a67531ffc4990c152d59ed0802e1c0caf7e27e424e9cea9ef3d499d4" # bin/update.py dprint
version = "--version"
modifier = "SHASUMS256.txt"

[uv]
url = "https://github.com/astral-sh/uv/releases/download/0.9.18/uv-x86_64-unknown-linux-gnu.tar.gz"
expected = "c2def3db178ade63933fa15ffc96e882c196ce53e06173dcee05b36c5f6f68f5" # bin/update.py uv
version = "--version"
prefix = "uv-x86_64-unknown-linux-gnu/"
ignore = ["uv-x86_64-unknown-linux-gnu"]
modifier = ".sha256"

[fnm]
# <https://github.com/Schniz/fnm/releases>, no checksums provided
url = "https://github.com/Schniz/fnm/releases/download/v1.38.1/fnm-linux.zip"
version = "--version"
expected = "b69e5c9a05c1e17e4a7de9a17df14ba430d049f2591af791a6f850a170296069"

[tofu]
url = "https://github.com/opentofu/opentofu/releases/download/v1.11.1/tofu_1.11.1_linux_amd64.zip"
modifier = "_SHA256SUMS"
expected = "bbfaf9baff1e5baf2775a4a9e7ba9e3c0152841f29f4ee7cf4610feb48f2db1c" # bin/update.py tofu
ignore = ["LICENSE", "README.md", "CHANGELOG.md"]
version = "version"

[yq]
url = "https://github.com/mikefarah/yq/releases/download/v4.50.1/yq_linux_amd64"
version = "--version"
expected = "c7a1278e6bbc4924f41b56db838086c39d13ee25dcb22089e7fbf16ac901f0d4" # bin/update.py yq
modifier = "checksums-bsd"

[jsonnet-lint]
url = "https://github.com/google/go-jsonnet/releases/download/v0.21.0/go-jsonnet_Linux_x86_64.tar.gz"
modifier = "checksums.txt"
expected = "ad3181fde77726b02d17eb4e72687020bf2cb35b9336cdeaaca4783c7ff104f7"
ignore = [
  "LICENSE",
  "README.md",
  "jsonnet",
  "jsonnetfmt",
  "jsonnet-deps",
]
version = "--version"

[jsonnet-language-server]
# https://github.com/grafana/jsonnet-language-server/releases/download/v0.16.0/jsonnet-language-server_0.16.0_checksums.txt
url = "https://github.com/grafana/jsonnet-language-server/releases/download/v0.16.0/jsonnet-language-server_0.16.0_linux_amd64"
expected = "42c7d38515e5a2008de26d678140e2d7fd1825eb977d78023fe997913e3dc2be"
version = "--version"

# bin/linux-amd64.toml
# Copyright Keith Maxwell
# SPDX-License-Identifier: CC0-1.0
