#!/usr/bin/env -S python3 bin/dotlocalslashbin.py --input
[a4]
url = "https://github.com/maxwell-k/a4/releases/download/0.2.1/a4"
expected = "a68b6bd92be782e109c5066da692d6463c807cf5213b732c4fe5e9e51bd194eb"
version = "--version"
modifier = "SHA256SUMS"

[actionlint]
url = "https://github.com/rhysd/actionlint/releases/download/v1.7.10/actionlint_1.7.10_linux_amd64.tar.gz"
expected = "f4c76b71db5755a713e6055cbb0857ed07e103e028bda117817660ebadb4386f"
modifier = "_checksums.txt"
ignore = [
  "LICENSE.txt",
  "README.md",
  "docs/README.md",
  "docs/api.md",
  "docs/checks.md",
  "docs/config.md",
  "docs/install.md",
  "docs/reference.md",
  "docs/usage.md",
  "man/actionlint.1",
]
version = "-version"

[deno]
url = "https://github.com/denoland/deno/releases/download/v2.6.4/deno-x86_64-unknown-linux-gnu.zip"
expected = "9100bbd0450c17b82002d3948bb8e7e1953c9e6506e63b586e2daa4042eca7f6"
target = "~/.deno/bin/deno"
version = "--version"
modifier = ".sha256sum"

[dprint]
url = "https://github.com/dprint/dprint/releases/download/0.51.1/dprint-x86_64-unknown-linux-gnu.zip"
expected = "674c1f9fcdf8a564c26cc027e080d0c4758a40a566e04a776fc83c875ad51d45"
version = "--version"
modifier = "SHASUMS256.txt"

[uv]
url = "https://github.com/astral-sh/uv/releases/download/0.9.21/uv-x86_64-unknown-linux-gnu.tar.gz"
expected = "0a1ab27383c28ef1c041f85cbbc609d8e3752dfb4b238d2ad97b208a52232baf"
version = "--version"
prefix = "uv-x86_64-unknown-linux-gnu/"
ignore = ["uv-x86_64-unknown-linux-gnu"]
modifier = ".sha256"

[fnm]
# <https://github.com/Schniz/fnm/releases>, no checksums provided
url = "https://github.com/Schniz/fnm/releases/download/v1.38.1/fnm-linux.zip"
version = "--version"
expected = "b69e5c9a05c1e17e4a7de9a17df14ba430d049f2591af791a6f850a170296069"

[tofu]
url = "https://github.com/opentofu/opentofu/releases/download/v1.11.2/tofu_1.11.2_linux_amd64.zip"
modifier = "_SHA256SUMS"
expected = "1bfb425c940098952df7a74e2f67dd318614bbea2767a25de94e46ca5d5b85ec"
ignore = ["LICENSE", "README.md", "CHANGELOG.md"]
version = "version"

[yq]
url = "https://github.com/mikefarah/yq/releases/download/v4.50.1/yq_linux_amd64"
version = "--version"
expected = "c7a1278e6bbc4924f41b56db838086c39d13ee25dcb22089e7fbf16ac901f0d4"
modifier = "checksums-bsd"

[jsonnet-lint]
url = "https://github.com/google/go-jsonnet/releases/download/v0.21.0/go-jsonnet_Linux_x86_64.tar.gz"
modifier = "checksums.txt"
expected = "ad3181fde77726b02d17eb4e72687020bf2cb35b9336cdeaaca4783c7ff104f7"
ignore = [
  "LICENSE",
  "README.md",
  "jsonnet",
  "jsonnetfmt",
  "jsonnet-deps",
]
version = "--version"

[jsonnet-language-server]
url = "https://github.com/grafana/jsonnet-language-server/releases/download/v0.16.0/jsonnet-language-server_0.16.0_linux_amd64"
expected = "42c7d38515e5a2008de26d678140e2d7fd1825eb977d78023fe997913e3dc2be"
version = "--version"
modifier = "_checksums.txt"

# bin/linux-amd64.toml
# Copyright Keith Maxwell
# SPDX-License-Identifier: CC0-1.0
