#!/usr/bin/env -S python3 bin/dotlocalslashbin.py
[a4]
url = "https://github.com/maxwell-k/a4/releases/download/0.2.3/a4"
expected = "2bfdd6dbba09955515ab96da76556b4929645979184f8d449e261874963ac3f7"
version = "--version"
modifier = "SHA256SUMS"

[actionlint]
url = "https://github.com/rhysd/actionlint/releases/download/v1.7.11/actionlint_1.7.11_linux_amd64.tar.gz"
expected = "900919a84f2229bac68ca9cd4103ea297abc35e9689ebb842c6e34a3d1b01b0a"
modifier = "_checksums.txt"
ignore = [
  "LICENSE.txt",
  "README.md",
  "docs/README.md",
  "docs/api.md",
  "docs/checks.md",
  "docs/config.md",
  "docs/install.md",
  "docs/reference.md",
  "docs/usage.md",
  "man/actionlint.1",
]
version = "-version"

[deno]
url = "https://github.com/denoland/deno/releases/download/v2.6.10/deno-x86_64-unknown-linux-gnu.zip"
expected = "a7c9d5c1f93bfaabe03c3c0583a8c88caf695db3cec4dea2938440038609f225"
target = "~/.deno/bin/deno"
version = "--version"
modifier = ".sha256sum"

[dprint]
url = "https://github.com/dprint/dprint/releases/download/0.51.1/dprint-x86_64-unknown-linux-gnu.zip"
expected = "674c1f9fcdf8a564c26cc027e080d0c4758a40a566e04a776fc83c875ad51d45"
version = "--version"
modifier = "SHASUMS256.txt"

[uv]
url = "https://github.com/astral-sh/uv/releases/download/0.10.4/uv-x86_64-unknown-linux-gnu.tar.gz"
expected = "6b52a47358deea1c5e173278bf46b2b489747a59ae31f2a4362ed5c6c1c269f7"
version = "--version"
prefix = "uv-x86_64-unknown-linux-gnu/"
modifier = ".sha256"

[fnm]
# <https://github.com/Schniz/fnm/releases>, no checksums provided
url = "https://github.com/Schniz/fnm/releases/download/v1.38.1/fnm-linux.zip"
version = "--version"
expected = "b69e5c9a05c1e17e4a7de9a17df14ba430d049f2591af791a6f850a170296069"

[tofu]
url = "https://github.com/opentofu/opentofu/releases/download/v1.11.5/tofu_1.11.5_linux_amd64.zip"
modifier = "_SHA256SUMS"
expected = "901121681e751574d739de5208cad059eddf9bd739b575745cf9e3c961b28a13"
version = "version"
ignore = [
  "CHANGELOG.md",
  "LICENSE",
  "README.md",
]

[yq]
url = "https://github.com/mikefarah/yq/releases/download/v4.52.4/yq_linux_amd64"
version = "--version"
expected = "0c4d965ea944b64b8fddaf7f27779ee3034e5693263786506ccd1c120f184e8c"
modifier = "checksums-bsd"

[jsonnet-lint]
url = "https://github.com/google/go-jsonnet/releases/download/v0.21.0/go-jsonnet_Linux_x86_64.tar.gz"
modifier = "checksums.txt"
expected = "ad3181fde77726b02d17eb4e72687020bf2cb35b9336cdeaaca4783c7ff104f7"
ignore = [
  "LICENSE",
  "README.md",
  "jsonnet",
  "jsonnetfmt",
  "jsonnet-deps",
]
version = "--version"

[jsonnet-language-server]
url = "https://github.com/grafana/jsonnet-language-server/releases/download/v0.17.0/jsonnet-language-server_0.17.0_linux_amd64"
expected = "1d4327c93505570d9e5bfe43c3b14da669c2e929c4ada3fcd6b4bf97c7cff34e"
version = "--version"
modifier = "_checksums.txt"

[beancount-language-server]
url = "https://github.com/polarmutex/beancount-language-server/releases/download/1.9.2/beancount-language-server-linux-x64.gz"
expected = "8f410c963cd2289bb0464b2d75ec7d46dfb5edd0dd6d4fc0dfab76b7225fe70d"
version = "--version"
modifier = ".sha256"

[jj]
url = "https://github.com/jj-vcs/jj/releases/download/v0.38.0/jj-v0.38.0-x86_64-unknown-linux-musl.tar.gz"
expected = "ed830d9a34a304f8ba258806b52521250a9fffded32ae89c4eb5285b33556a17"
ignore = [
  "./LICENSE",
  "./README.md",
]
version = "--version"

[typst]
url = "https://github.com/typst/typst/releases/download/v0.14.2/typst-x86_64-unknown-linux-musl.tar.xz"
expected = "a6044cbad2a954deb921167e257e120ac0a16b20339ec01121194ff9d394996d"
prefix = "typst-x86_64-unknown-linux-musl/"
ignore = [
  "NOTICE",
  "LICENSE",
  "README.md",
]
version = "--version"

[rclone]
url = "https://github.com/rclone/rclone/releases/download/v1.72.0/rclone-v1.72.0-linux-amd64.zip"
expected = "f3757aa829828c0f3359301bea25eef4d4fd62de735c47546ee6866c5b5545e2"
version = "version"
modifier = "SHA256SUMS"
prefix = "rclone-v1.72.0-linux-amd64/" # depName=rclone/rclone
ignore = [
  "README.txt",
  "README.html",
  "rclone.1",
  "git-log.txt",
]

# bin/linux-amd64.toml
# Copyright Keith Maxwell
# SPDX-License-Identifier: CC0-1.0
