#!/usr/bin/env -S python3 bin/dotlocalslashbin.py --input
[pip]
# https://pip.pypa.io/en/stable/installation/
url = "https://bootstrap.pypa.io/pip/zipapp/pip-26.0.pyz"
version = "--version"
command = "python3.13 -m zipapp --python=/usr/bin/python3.13 --output={target} {downloaded}"

[python]
url = "/usr/bin/python3.13"
version = "--version"

# bin/python.toml
# Copyright Keith Maxwell
# SPDX-License-Identifier: CC0-1.0
