line-length = 88
indent-width = 4
target-version = "py313"

[lint]
select = ["ALL"]
ignore = [ # see https://docs.astral.sh/ruff/rules/
  "D203", # incompatible with D211
  "D213", # incompatible with D212
  "I", # prefer usort to ruff isort implementation
  "PT", # prefer unittest style
  "S310", # "use instead" code from the documentation triggers this warning
  "S602", # assume arguments to subprocess.run are validated
  "S603", # assume trusted input to subprocess.run
  "T201", # allow print for output in command line scripts
]
#
# .ruff.toml
# SPDX-FileCopyrightText: 2025 Keith Maxwell <keith.maxwell@gmail.com>
# SPDX-License-Identifier: CC0-1.0
